### ISSUE TITLE
/usr/bin/ld: cannot find -lpthreads  (same with#230)

### ISSUE THREAD

**Issue by 405755490** [cinemast/libjson-rpc-cpp#236]
linux version: aliyun centos 7.3

dependencies some are not installed（libmicrohttpd libargtable catch）

Linux version 3.10.0-514.26.2.el7.x86_64  (gcc version 4.8.5 20150623 (Red Hat 4.8.5-11) (GCC) )   
GNU Make 3.82
cmake version 3.5.2 
after update cmake version to 3.11.3 , have the same error 

find / -name "*pthread.so"

/usr/lib64/libpthread.so.0
/usr/lib64/libpthread.so
/usr/lib64/libgpgme-pthread.so.11.8.1
/usr/lib64/libpthread-2.17.so
/usr/lib64/libgpgme-pthread.so.11

error info:
Determining if the pthread_create exist failed with the following output:
Change Dir: /home/github/json_rpc_cpp/libjson-rpc-cpp/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/gmake" "cmTC_44f39/fast"
/usr/bin/gmake -f CMakeFiles/cmTC_44f39.dir/build.make CMakeFiles/cmTC_44f39.dir/build
gmake[1]: Entering directory `/home/github/json_rpc_cpp/libjson-rpc-cpp/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_44f39.dir/CheckSymbolExists.c.o
/usr/bin/cc    -o CMakeFiles/cmTC_44f39.dir/CheckSymbolExists.c.o   -c /home/github/json_rpc_cpp/libjson-rpc-cpp/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c
Linking C executable cmTC_44f39
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_44f39.dir/link.txt --verbose=1
/usr/bin/cc      -rdynamic CMakeFiles/cmTC_44f39.dir/CheckSymbolExists.c.o  -o cmTC_44f39 
CMakeFiles/cmTC_44f39.dir/CheckSymbolExists.c.o: In function `main':
CheckSymbolExists.c:(.text+0x16): undefined reference to `pthread_create'
collect2: error: ld returned 1 exit status
gmake[1]: *** [cmTC_44f39] Error 1
gmake[1]: Leaving directory `/home/github/json_rpc_cpp/libjson-rpc-cpp/build/CMakeFiles/CMakeTmp'
gmake: *** [cmTC_44f39/fast] Error 2

File /home/github/json_rpc_cpp/libjson-rpc-cpp/build/CMakeFiles/CMakeTmp/CheckSymbolExists.c:
/* */
#include <pthread.h>

int main(int argc, char** argv)
{
  (void)argv;
#ifndef pthread_create
  return ((int*)(&pthread_create))[argc];
#else
  (void)argc;
  return 0;
#endif
}

Determining if the function pthread_create exists in the pthreads failed with the following output:
Change Dir: /home/github/json_rpc_cpp/libjson-rpc-cpp/build/CMakeFiles/CMakeTmp

Run Build Command:"/usr/bin/gmake" "cmTC_0f621/fast"
/usr/bin/gmake -f CMakeFiles/cmTC_0f621.dir/build.make CMakeFiles/cmTC_0f621.dir/build
gmake[1]: Entering directory `/home/github/json_rpc_cpp/libjson-rpc-cpp/build/CMakeFiles/CMakeTmp'
Building C object CMakeFiles/cmTC_0f621.dir/CheckFunctionExists.c.o
/usr/bin/cc   -DCHECK_FUNCTION_EXISTS=pthread_create   -o CMakeFiles/cmTC_0f621.dir/CheckFunctionExists.c.o   -c /usr/local/share/cmake-3.11/Modules/CheckFunctionExists.c
Linking C executable cmTC_0f621
/usr/local/bin/cmake -E cmake_link_script CMakeFiles/cmTC_0f621.dir/link.txt --verbose=1
/usr/bin/cc  -DCHECK_FUNCTION_EXISTS=pthread_create    -rdynamic CMakeFiles/cmTC_0f621.dir/CheckFunctionExists.c.o  -o cmTC_0f621 -lpthreads 
/bin/ld: cannot find -lpthreads
collect2: error: ld returned 1 exit status
gmake[1]: *** [cmTC_0f621] Error 1
gmake[1]: Leaving directory `/home/github/json_rpc_cpp/libjson-rpc-cpp/build/CMakeFiles/CMakeTmp'
gmake: *** [cmTC_0f621/fast] Error 2

**Comment by cinemast** [comment]
I see from the log you are using RedHat 4.8 which got released in 2009. Please use a more recent distro.
