### ISSUE TITLE
Ubuntu "undefined reference" after update from 0.5.0 to 0.6.0 

### ISSUE THREAD

**Issue by BuilovAlexey** [cinemast/libjson-rpc-cpp#131]
I use Clion on Ubuntu. Yesterday I update libjsonrpccpp-dev and libjsonrpccpp-tools from 0.5.0 to 0.6.0. After build my test project I get exception:
```undefined reference to `jsonrpc::HttpClient::HttpClient(std::string const&)' ```. 
Before update my test project work and i can link libraries.

At all I install libjsonrpccpp-dev, libjsonrpccpp-tools, libjsoncpp-dev, libcurl and something else.

main.cpp :
```
#include <iostream>
#include <wchar.h>
#include <string>
#include <stdlib.h>
#include "stdio.h"
#include <jsonrpccpp/client.h>
#include <jsonrpccpp/client/connectors/httpclient.h>
using namespace jsonrpc;
using namespace Json;
using namespace std;
int main() {
	HttpClient httpClient("http://localhost:3333/");
	Client clientNew(httpClient);
}
```
Cmakelists:
```
cmake_minimum_required(VERSION 3.2)
project(testHttp)
set(CMAKE_CXX_FLAGS "${CMAKE_CXX_FLAGS} -std=c++11 ")
set(INCLUDE_DIRECTORIES "/usr/include" "/usr/include/jsonrpccpp" "/usr/include/jsoncpp" "/usr/include/curl")
include_directories("${INCLUDE_DIRECTORIES}" )
set( REQUIRED_LIBRARIES jsonrpccpp-client jsonrpccpp-common jsonrpccpp-server jsoncpp curl)
link_directories( "/usr/lib/x86_64-linux-gnu" )
set(SOURCE_FILES main.cpp)
add_executable(testHttp ${SOURCE_FILES})
target_link_libraries (testHttp "${REQUIRED_LIBRARIES}")
```

What i can do with this? :( May be i will download 0.5.0 release and build this, but i hope you help me with 0.6.0 version.

P.S. Sorry for my english. I am from Russia :)

**Comment by cinemast** [comment]
Did you update using the ubuntu package or did you get the latest release here and compiled + installed on your own?

**Comment by BuilovAlexey** [comment]
i install them : "sudo aptitude install libjsonrpccpp-dev libjsonrpccpp-tools"
and press yes,yes,yes. they updated. 
a was copy some of install log from terminal from this process: 
```
Будут установлены следующие дополнительные пакеты:
(translate: Will be installed nest additional packages)
 cmake cmake-data gcc-5-base gcc-5-base:i386 lib32atomic1 lib32cilkrts5
 lib32gcc1 lib32gomp1 lib32itm1 lib32quadmath0 lib32stdc++6 lib32ubsan0
 libatomic1 libcilkrts5 libgcc1 libgcc1:i386 libgomp1 libitm1 libjsoncpp-dev
 libjsoncpp0v5 libjsonrpccpp-client0 libjsonrpccpp-common0
 libjsonrpccpp-server0 libjsonrpccpp-stub0 liblsan0 libquadmath0 libstdc++6
 libtsan0 libubsan0 libx32atomic1 libx32cilkrts5 libx32gcc1 libx32gomp1
 libx32itm1 libx32quadmath0 libx32stdc++6 libx32ubsan0
Пакеты, которые будут УДАЛЕНЫ:
(translate: The packages that will be REMOVED)
 libjsoncpp0
НОВЫЕ пакеты, которые будут установлены:
(translate: NEW packages that will be installed:)
 libjsoncpp0v5 libjsonrpccpp-stub0

Пакеты, которые будут обновлены:
(translate: packages that will be updated)
 cmake cmake-data gcc-5-base gcc-5-base:i386 lib32atomic1 lib32cilkrts5
 lib32gcc1 lib32gomp1 lib32itm1 lib32quadmath0 lib32stdc++6 lib32ubsan0
 libatomic1 libcilkrts5 libgcc1 libgcc1:i386 libgomp1 libitm1 libjsoncpp-dev
 libjsonrpccpp-client0 libjsonrpccpp-common0 libjsonrpccpp-dev
 libjsonrpccpp-server0 liblsan0 libquadmath0 libstdc++6 libtsan0 libubsan0
 libx32atomic1 libx32cilkrts5 libx32gcc1 libx32gomp1 libx32itm1
 libx32quadmath0 libx32stdc++6 libx32ubsan0```

**Comment by BuilovAlexey** [comment]
now i get 0.5.0 release and build my test project with link to building libraries. In last update of packages i update libjsoncpp-dev. As a result i link libjsonrpccpp libraries, but a get exception with link to libjsoncpp libs:
```
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libjsonrpccpp-client.so: undefined reference to `Json::Value::Value(std::string const&)'
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libjsonrpccpp-client.so: undefined reference to `Json::FastWriter::write(Json::Value const&)'
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libjsonrpccpp-client.so: undefined reference to `Json::Reader::parse(std::string const&, Json::Value&, bool)'
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libjsonrpccpp-common.so: undefined reference to `Json::Value::getMemberNames() const'
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libjsonrpccpp-client.so: undefined reference to `Json::Value::toStyledString() const'
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libjsonrpccpp-client.so: undefined reference to `Json::Value::asString() const'
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libjsonrpccpp-client.so: undefined reference to `Json::Value::operator[](std::string const&)'
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libjsonrpccpp-client.so: undefined reference to `Json::Value::operator[](std::string const&) const'
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libjsonrpccpp-client.so: undefined reference to `Json::Value::isMember(std::string const&) const'
/usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/libjsonrpccpp-client.so: undefined reference to `Json::StyledWriter::write(Json::Value const&)'
```

**Comment by BuilovAlexey** [comment]
I download jsoncpp 0.10.2 release. build and use generated libs. and I can success start my test project. WTF :(
I can use this build, but all network repositories have last BAD release. and if i will need download packages from repo-ies, a can't do this...
Fix this problem pls. or say me, what i do wrong with new Jsoncpp and libjsonrpccpp project version. 
Jsoncpp project have bad release (a wrote earlier that).

**Comment by cinemast** [comment]
Hi!

I guess you are using the alpha release of Ubuntu (wily). It seems that you are compiling your test program with gcc 4.9.x. 

The packages you are using are probably built with gcc 5.x. gcc 4.9 and gcc 5 are ABI incompatible, which means you cannot link against libraries built with a different compiler version. 

So I think using gcc5 to compile your test program would fix this error. I cannot support anything that is currently in alpha testing phase.

There is no BAD release of jsoncpp nor libjson-rpc-cpp. This is simply an issue with your linux distribution and different gcc versions.

Please let me know if that fixes your problem.

**Comment by BuilovAlexey** [comment]
yes use wily mail universe.

I don't understand... What different between libjson-rpc-cpp v. 0.5.0 and 0.6.0?
0.5.0 was build with gcc 4.9 and 0.6.0 - with gcc 5.0? and i need upgrade my gcc. and after that link libjsonrpccpp libs will be success?

**Comment by cinemast** [comment]
Exactly. I don't have any influence on that. The GCC team broke the ABI with version 5.

**Comment by BuilovAlexey** [comment]
Okey, thanks for help with link to lins.
Links to libjsonrpccpp and ligjsoncpp libs are success now.


But now I get exception when call server method.
```Exception -32003 : Client connector error: libcurl error: 56```


``` Json::Value params;
params["testArg"] = 1;
HttpClient httpClient("http://localhost:3333/");
httpClient.SetTimeout(10000);
Client clientNew(httpClient);
Value methodResult = clientNew.CallMethod("testMethod2", params); !!!!!!!!!!! in this point:
```
I logging server and i know that method "testMethod2" called. But response can't come back to client.
Before update to 0.6.0 version jsonrpc and json libs, I can get normal response, i get "methodResult".

What do you think about this problem?

**Comment by cinemast** [comment]
Without seeing or knowing more about the server, I can't tell. 

http://curl.haxx.se/libcurl/c/libcurl-errors.html

error 56 means there is something wrong with the result. What I do in such situations is starting [wireshark](http://wiki.ubuntuusers.de/wireshark) and check what exactly has been transmitted between client and server.

**Comment by BuilovAlexey** [comment]
Hm... I test my project on VirtualBox in Windows. I start my server by mono with this command: 
```sudo mono server.exe```
server write by c#. It's work. Method result come back.
But i get libcurl error: 56 if i start server without "sudo".
But when i test this in Parallels in Mac os i get 
```Exception -32003 : Client connector error: libcurl error: 56```
With sudo or without this. I think i haven't permissions for something. Or firewall is reason.
What do you think?

**Comment by BuilovAlexey** [comment]
okey it's was exception related with streams. thanks

**Comment by cinemast** [comment]
Alright, thanks for closing the issue.
